from __future__ import annotations


LABELS = {
    "en": {
        "brand": "Nova Insight",
        "health_title": "PROJECT HEALTH",
        "predictive_title": "PREDICTIVE",
        "subtitle": "What should I act on today?",
        "filters": "Filters",
        "all": "All",
        "all_items": "All",
        "now": "Now",
        "unassigned": "Unassigned",
        "building": "Building / Area",
        "phase": "Phase",
        "floor": "Floor",
        "trade": "Trade / Discipline",
        "task_type": "Task Type",
        "activities_analyzed": "Activities analyzed",
        "critical_activities": "Critical activities",
        "point_no_return": "Point of no return",
        "delayed_activities": "Delayed activities",
        "important_next": "Important next",
        "monitor": "Monitor",
        "highest_risk": "Highest risk",
        "graph_title_health": "Progress Over Time",
        "graph_title_predictive": "Schedule Risk Outlook",
        "graph_subtitle_health": "Planned vs actual progress from available schedule data",
        "graph_subtitle_predictive": "Actual progress and delay risk from available schedule data",
        "actual": "Actual",
        "planned": "Schedule",
        "forecast": "Forecast",
        "delay": "Delay",
        "today": "Today",
        "finish_late": "Finish late",
        "data_quality": "Data quality",
        "no_graph_data": "Not enough progress data to render a reliable curve.",
        "area_progress": "Current Extract",
        "area_progress_sub": "Ranked area / phase progress",
        "progress": "Progress",
        "behind_table": "Behind Schedule",
        "ahead_table": "Ahead of Schedule",
        "changed_table": "Changed Activities",
        "stage_table": "Current Stage Analysis",
        "critical_path_table": "Critical Path Activities",
        "kemp_details": "Advanced details",
        "kemp_toggle_label": "Show Full overview",
        "overview_label": "Overview",
        "overview_toggle_label": "Show Overview",
        "summary_notes": "Summary & Notes",
        "summary_notes_sub": "Report facts for export and handover",
        "analysis_generated": "Analysis generated",
        "old_schedule_date": "Old schedule date",
        "new_schedule_date": "New schedule date",
        "actions": "What Should You Do Now",
        "critical_now": "Critical Now",
        "all_delayed": "All Delayed Activities",
        "root_causes": "Root Causes",
        "id": "ID",
        "task_name": "Activity Name",
        "phase_col": "Phase",
        "actual_col": "Actual",
        "expected_col": "Expected",
        "deviation_col": "Deviation",
        "ahead_col": "Ahead",
        "start_col": "Start",
        "finish_col": "Finish",
        "duration_col": "Duration",
        "old_start_col": "Old start",
        "new_start_col": "New start",
        "old_finish_col": "Old finish",
        "new_finish_col": "New finish",
        "old_duration_col": "Old duration",
        "new_duration_col": "New duration",
        "change_col": "Change",
        "before_col": "Before",
        "after_col": "After",
        "float_col": "Float",
        "not_available": "N/A",
        "completed_activities": "Completed activities",
        "total_activities": "Total activities",
        "removed_activities": "Removed activities",
        "added_activities": "Added activities",
        "overall_progress": "Overall progress",
        "reporting_period": "Reporting period",
        "notes": "Notes",
        "risk_bucket_note": "Delay aging view based on delayed activities; this is not a progress-over-time curve.",
        "no_notes": "No additional notes.",
        "new_start": "New start",
        "new_finish": "New finish",
        "status_col": "Status",
        "days_overdue": "Days overdue",
        "priority": "Priority",
        "sort": "Sort",
        "none": "None",
    },
    "da": {
        "brand": "Nova Insight",
        "health_title": "PROJEKTSUNDHED",
        "predictive_title": "PROGNOSE",
        "subtitle": "Hvad skal jeg handle på i dag?",
        "filters": "Filtre",
        "all": "Alle",
        "all_items": "Alle",
        "now": "Nu",
        "unassigned": "Ikke tildelt",
        "building": "Bygning / Område",
        "phase": "Fase / Etape",
        "floor": "Etage",
        "trade": "Fag / Disciplin",
        "task_type": "Opgavetype",
        "activities_analyzed": "Aktiviteter analyseret",
        "critical_activities": "Kritiske aktiviteter",
        "point_no_return": "Point of no return",
        "delayed_activities": "Forsinkede aktiviteter",
        "important_next": "Vigtig næste",
        "monitor": "Overvåg",
        "highest_risk": "Største risiko",
        "graph_title_health": "Fremdrift over tid",
        "graph_title_predictive": "Risiko og prognose",
        "graph_subtitle_health": "Planlagt vs faktisk fremdrift fra tilgængelige tidsplandata",
        "graph_subtitle_predictive": "Faktisk fremdrift og forsinkelsesrisiko fra tilgængelige tidsplandata",
        "actual": "Faktisk",
        "planned": "Plan",
        "forecast": "Prognose",
        "delay": "Forsinkelse",
        "today": "I dag",
        "finish_late": "Slutter sent",
        "data_quality": "Datakvalitet",
        "no_graph_data": "Ikke nok fremdriftsdata til at vise en pålidelig kurve.",
        "area_progress": "Aktuelt udtræk",
        "area_progress_sub": "Rangeret område / fase-fremdrift",
        "progress": "Fremdrift",
        "behind_table": "Bagud i planen",
        "ahead_table": "Foran planen",
        "changed_table": "Ændrede aktiviteter",
        "stage_table": "Analyse af stade d.d.",
        "critical_path_table": "Kritiske vej-aktiviteter",
        "kemp_details": "Avancerede detaljer",
        "kemp_toggle_label": "Vis Fuld oversigt",
        "overview_label": "Overblik",
        "overview_toggle_label": "Vis fuld oversigt",
        "summary_notes": "Opsummering & noter",
        "summary_notes_sub": "Rapportfakta til eksport og overlevering",
        "analysis_generated": "Analyse genereret",
        "old_schedule_date": "Gammel plan dato",
        "new_schedule_date": "Ny plan dato",
        "actions": "Hvad skal du gøre nu",
        "critical_now": "Kritisk nu",
        "all_delayed": "Alle forsinkede aktiviteter",
        "root_causes": "Rodårsager",
        "id": "ID",
        "task_name": "Emne / Opgavenavn",
        "phase_col": "Etape / fase",
        "actual_col": "Oplyst stade",
        "expected_col": "Stade planlagt",
        "deviation_col": "Afvigelse",
        "ahead_col": "Forspring",
        "start_col": "Startdato",
        "finish_col": "Slutdato",
        "duration_col": "Varighed",
        "old_start_col": "Gammel start",
        "new_start_col": "Ny start",
        "old_finish_col": "Gammel slut",
        "new_finish_col": "Ny slut",
        "old_duration_col": "Gammel varighed",
        "new_duration_col": "Ny varighed",
        "change_col": "Ændring",
        "before_col": "Før",
        "after_col": "Efter",
        "float_col": "Float",
        "not_available": "Ikke oplyst",
        "completed_activities": "Afsluttede aktiviteter",
        "total_activities": "Aktiviteter i alt",
        "removed_activities": "Fjernede aktiviteter",
        "added_activities": "Tilføjede aktiviteter",
        "overall_progress": "Samlet fremdrift",
        "reporting_period": "Rapporteringsperiode",
        "notes": "Noter",
        "risk_bucket_note": "Forsinkelsesalder baseret på forsinkede aktiviteter; dette er ikke en fremdriftskurve over tid.",
        "no_notes": "Ingen yderligere noter.",
        "new_start": "Ny startdato",
        "new_finish": "Ny slutdato",
        "status_col": "Status",
        "days_overdue": "Dage over",
        "priority": "Prioritet",
        "sort": "Sorter",
        "none": "Ingen",
    },
}


def lang_code(language: str) -> str:
    return "da" if str(language).lower().startswith("da") else "en"


def t(language: str, key: str) -> str:
    code = lang_code(language)
    return LABELS.get(code, LABELS["en"]).get(key, LABELS["en"].get(key, key))
